### ISSUE TITLE
Cannot add links with special characters to a list

### ISSUE THREAD

**Issue by Lukas34** [burkeholland/the-urlist#26]
When trying to add a link with special characters (for example: ä, ü, ö) they automatically get converted to ASCII values (for example: %A4, %C3) when copy and pasting, which is normal, but that will throw an error when you try to add that link to a collection.

Example link: https://de.wikipedia.org/wiki/Di%C3%A4t (A german wikipedia site)
![image](https://user-images.githubusercontent.com/36658128/57795611-b3d4e200-7746-11e9-9c21-f83ad9a27f21.png)

**Comment by cecilphillip** [comment]
@Lukas34 Thanks for reporting. I'll take a look at this

**Comment by cecilphillip** [comment]
moving to the-urlist/home#5
